# encoding: utf-8

SEARCH_API_RESPONSE_KEYS = ["ip",
 "domain_name",
 "domain_type",
 "line_code",
 "line_j_name",
 "line_c_f",
 "proxy_flag",
 "time_zone",
 "continent_code",
 "country_code",
 "country_a_name",
 "country_j_name",
 "region_code",
 "pref_code",
 "pref_a_name",
 "pref_j_name",
 "pref_latitude",
 "pref_longitude",
 "pref_c_f",
 "city_code",
 "city_a_name",
 "city_j_name",
 "city_latitude",
 "city_longitude",
 "city_c_f",
 "b_c_flag",
 "org_code",
 "org_office_code",
 "org_independent_code",
 "org_name",
 "org_english_name",
 "org_pref_code",
 "org_city_code",
 "org_latitude",
 "org_longitude",
 "org_zip_code",
 "org_address",
 "org_english_address",
 "org_tel",
 "org_fax",
 "org_ipo_type",
 "stock_ticker_number",
 "org_date",
 "org_capital_code",
 "org_employees_code",
 "org_gross_code",
 "org_president",
 "org_industrial_category_l",
 "org_industrial_category_m",
 "org_industrial_category_s",
 "org_industrial_category_t",
 "tel_code",
 "org_url",
 "org_domain_name",
 "org_domain_type"]


__END__

